stages:
  - build
  - test
  - build-frontend
  - sonarqube-check
  - docker-compose

build:
  stage: build
  script:
    - cd IndividualTrack 
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - cd IndividualTrack
    - ./gradlew test
    - ./gradlew.bat --stop

build-frontend:
  stage: build-frontend
  script:
    - cd FrontEnd
    - cd Front_end_nba
    - cd nba-portal
    - npm install      # Run `npm install` and `npm build`
    - npm test

sonarqube-check:
  stage: sonarqube-check
  script:
    - cd IndividualTrack
    - ./gradlew sonarqube
    - ./gradlew.bat --stop
  allow_failure: true
  only:
    - main

docker-compose:
  stage: docker-compose
  image: docker
  services:
    - docker:dind
  only:
    - main
  script:
    - docker --version
    - docker-compose --version
    - docker-compose build backend
    - docker-compose build frontend
    - docker-compose up -d
  timeout: 3 minutes



