variables:
  GIT_STRATEGY: clone

stages:
  - build
  - test
  - sonarqube-check
  - docker-compose
  - frontend-test

build:
  stage: build
  script:
    - cd IndividualTrack
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - cd IndividualTrack
    - ./gradlew test
    - ./gradlew.bat --stop

docker-compose:
  stage: docker-compose
  image: docker
  services:
    - docker:dind
  only:
    - main
  script:
    - docker --version
    - docker-compose --version
    - cd IndividualTrack
    - ./gradlew assemble
    - cd ..
    - docker-compose build backend
    - docker-compose build frontend
    - docker-compose up -d
  timeout: 10 minutes

frontend-test:
  stage: frontend-test
  image: cypress/base:10
  script:
    - cd FrontEnd
    - cd Front_end_nba
    - cd nba-portal
    - npm install
    - npm run cypress:runHeadless
  allow_failure: true

sonarqube-check:
  stage: sonarqube-check
  image: gradle:jre11-slim
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd IndividualTrack
    - ./gradlew jacocoTestReport
    - ./gradlew sonarqube
    - ./gradlew.bat --stop
  allow_failure: true
  timeout: 5 minutes
  only:
    - main




