stages:
-build
-test

build:
stage: build
script:
- cd individual-track
- ./gradlew build -x test
- ./gradlew.bat --stop

test:
stage: test
script:
- cd individual-track
- ./gradlew test
- ./gradlew.bat --stop
