stages:
  - build
  - test
  - build-frontend
  - sonarqube-check

build:
  stage: build
  script:
    - cd IndividualTrack 
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - cd IndividualTrack
    - ./gradlew test
    - ./gradlew.bat --stop

build-frontend:
  image: node:latest    # Run the job in a `node` docker image
  stage: build-frontend
  script:
    - cd FrontEnd
    - cd Front_end_nba
    - cd nba-portal
    - npm install      # Run `npm install` and `npm build`
    - npm test

sonarqube-check:
  stage: sonarqube-check
  script:
    - cd IndividualTrack
    - ./gradlew sonarqube
    - ./gradlew.bat --stop
  allow_failure: true
  #only:
   # - main# or the name of your main branch



