variables:
  GIT_STRATEGY: clone

stages:
  - build
  - docker-compose
  - test
  - sonarqube-check

build:
  stage: build
  script:
    - cd IndividualTrack
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - cd IndividualTrack
    - ./gradlew test
    - ./gradlew.bat --stop

docker-compose:
  stage: docker-compose
  image: docker
  services:
    - docker:dind
  only:
    - main
  script:
    - docker --version
    - docker-compose --version
   # - docker-compose build backend
   # - docker-compose build frontend
    - docker-compose start
  timeout: 3 minutes

sonarqube-check:
  stage: sonarqube-check
  script:
    - cd IndividualTrack
    - ./gradlew sonarqube
    - ./gradlew.bat --stop
  allow_failure: true
  only:
    - main




