version: '3.8'

services:
  db:
    container_name: mysql_c2
    image: mysql
    ports:
      - '3308:3306'
    expose:
      - '3306'
    restart: always
    environment:
      MYSQL_DATABASE: 'nba-portal'
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'

  backend:
    build:
      context: IndividualTrack
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/nba-portal
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  frontend:
    build:
      context: FrontEnd/Front_end_nba/nba-portal
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - backend